### ISSUE TITLE
Error when hooks are enabled

### ISSUE THREAD

**Issue by bogdancondorachi** [johannschopplich/kirby-algolia-docsearch#4] opened 2023-12-14 08:59 UTC
I've enabled the new hooks to index pages on changes but I get the following error when trying to save a page. This resulted in a weird behavior that only logged-in users could see the changes in the front end though on the panel it still appears as unsaved changes.

Also, I don't get the same error on localhost

`Class “JohannSchopplich\Algolia\Str” not found`

**Comment by johannschopplich** [comment] 2023-12-14 09:43
Hi there,

the issue you describe sounds weird indeed. Can you please provide a minimum reproducible example? A repo would be great, so I can test it. Thanks! 🙂

**Comment by johannschopplich** [comment] 2023-12-14 10:05
Quick question: Do you use the `Str` Kirby class in one of your pages, like `Str::startsWith()`?

**Comment by bogdancondorachi** [comment] 2023-12-14 10:16
Oh, now that you mention it, I DO

I have modified your plugin on the hierarchy part to show search results filtered by its parent as a specific need for a docs like kirby setup, you can view it here: [https://wiki.cloudfactory.com/](https://wiki.cloudfactory.com/)

Here's what the modified code looks like, though I haven't touch this since v3 and it might not be the best implementation
```php
'hierarchy' => [
  'lvl0' => (
    array_reduce(array_keys($label['parents']),
      function ($carry, $key) use ($page, $label) {
        return Str::startsWith($page->id(), $key)
        ? $label['parents'][$key]
        : $carry;
      },
      $label['templates'][$pageTemplate][$languageCode]
      ?? $label['templates'][$pageTemplate]
      ?? $label['default'][$languageCode]
      ?? $label['default']
    )
  ),
  'lvl1' => $page->content($languageCode)->get('title')->value()
]
``` 

And difined the parents in the config like this:
```
'label' => [
      'default' => 'Page',
      'templates' => [
        'doc-article' => 'Article'
      ],
      'parents' => [
        'docs/userdocs' => 'User Docs',
        'docs/mp-wiki' => 'MP Wiki'
      ]
]
``` 

Giving all this, adding `use Kirby\Toolkit\Str` to your plugin cloud solves it.

**Comment by johannschopplich** [comment] 2023-12-14 10:21
I see. The class import is required, otherwise `Str` is expected on the Algolia class. Closing this, as not a bug of the Algolia plugin.

**Closed as completed by johannschopplich** 2023-12-14 10:21 UTC
Labels: needs reproduction

**Comment by johannschopplich** [comment] 2023-12-14 10:26
By the way, feel free to open an PR for a custom filter method as a global config option. 🙌
